DATA EMPLOYEE2;
INFILE '/home/u63606353/sasuser.v94/csv/employee_data_200_1' DSD MISSOVER FIRSTOBS=2;
INPUT A B$ C$ D$ E$ F$ G$ H$ I$ J$ K$ L$ M$ N$ O$ P$ Q$ R$ S$ T$ U$ V$ W$ X$ Y$ Z$;
RUN;

DATA EMP_FEM;
SET EMPLOYEE2;
IF V = 'Female';
RUN;

/*
PROC SQL;
	SELECT | CAMPOS AGRUPADORES |,| FUNNCIONES DE AGREGADO | FROM TABLE
	GROUP BY | CAMPOS AGRUPADORES;
QUIT;
*/

PROC SQL; 
	SELECT G,V ,Y, COUNT(Z) AS CONTEO FROM EMPLOYEE2
	GROUP BY G,V,Y;
	ORDER BY CONTEO DESC;
QUIT;

/*PRIMERA CONSULTA */

PROC SQL;
	SELECT G,COUNT(Z) AS CONTEO1 FROM EMPLOYEE2
	GROUP BY G;
QUIT;

/*SEGUNDA CONSULTA */
PROC SQL;
	SELECT V,COUNT(Z) AS CONTEO2 FROM EMPLOYEE2
	GROUP BY V;
QUIT;

/*TERCERA CONSULTA*/

PROC SQL;
	SELECT Y,COUNT(Z) AS CONTEO3 FROM EMPLOYEE2
	GROUP BY Y;
QUIT;